import '../../services/constant.dart';
import '../../utils/helper.dart';

abstract class SettingsRepository {
  String getLanguageCode();
  Future<void> setLanguageCode(String value);
  UpdateChannel getUpdateChannel();
  Future<void> setUpdateChannel(UpdateChannel value);
  bool getNewVersionVisibility(bool fallback);
  Future<void> setNewVersionVisibility(bool enabled);
  bool getCacheSongs();
  Future<void> setCacheSongs(bool value);
  bool getSkipSilenceEnabled();
  Future<void> setSkipSilenceEnabled(bool value);
  bool getLoudnessNormalizationEnabled();
  Future<void> setLoudnessNormalizationEnabled(bool value);
  int getStreamingQualityIndex();
  Future<void> setStreamingQualityIndex(int value);
  int getThemeModeType();
  Future<void> setThemeModeType(int value);
  int getThemePrimaryColor();
  Future<void> setThemePrimaryColor(int value);
  String getDiscoverContentType();
  Future<void> setDiscoverContentType(String value);
  bool getQueueLoopModeEnabled();
  Future<void> setQueueLoopModeEnabled(bool value);
  bool getLoopModeEnabled();
  Future<void> setLoopModeEnabled(bool value);
  bool getShuffleModeEnabled();
  Future<void> setShuffleModeEnabled(bool value);
  int getVolume({int defaultValue = 100});
  Future<void> setVolume(int value);
  bool getBottomNavBarEnabled();
  Future<void> setBottomNavBarEnabled(bool value);
  int getNoOfHomeScreenContent();
  Future<void> setNoOfHomeScreenContent(int value);
  bool getTransitionAnimationDisabled();
  Future<void> setTransitionAnimationDisabled(bool value);
  bool getAutoOpenPlayer();
  Future<void> setAutoOpenPlayer(bool value);
  bool getRestorePlaybackSession();
  Future<void> setRestorePlaybackSession(bool value);
  bool getCacheHomeScreenData();
  Future<void> setCacheHomeScreenData(bool value);
  bool getDeveloperSettingsEnabled();
  Future<void> setDeveloperSettingsEnabled(bool value);
  int getPlaybackModeIndex();
  PlaybackMode getPlaybackMode();
  Future<void> setPlaybackMode(PlaybackMode mode);
  int getPlaybackPreloadRange();
  Future<void> setPlaybackPreloadRange(int value);
  int getPlayerUi();
  Future<void> setPlayerUi(int value);
  int getLyricsMode();
  Future<void> setLyricsMode(int value);
  bool getBackgroundPlayEnabled();
  Future<void> setBackgroundPlayEnabled(bool value);
  bool getKeepScreenAwake(bool fallback);
  Future<void> setKeepScreenAwake(bool value);
  String? getDownloadLocationPath();
  Future<void> setDownloadLocationPath(String value);
  String getExportLocationPath();
  Future<void> setExportLocationPath(String value);
  String getDownloadingFormat();
  Future<void> setDownloadingFormat(String value);
  bool getSlidableActionEnabled();
  Future<void> setSlidableActionEnabled(bool value);
  bool getAutoDownloadFavoriteSongEnabled();
  Future<void> setAutoDownloadFavoriteSongEnabled(bool value);
  int getLibraryFirstTab();
  Future<void> setLibraryFirstTab(int value);
  bool getBatteryOptimizationPromptShown();
  Future<void> setBatteryOptimizationPromptShown(bool value);
  Map<dynamic, dynamic>? getPiped();
  Future<void> setPiped(Map<dynamic, dynamic> value);
  Future<void> deletePiped();
  String? getVisitorId();
  Map<dynamic, dynamic>? getVisitorData();
  Future<void> setVisitorData(Map<dynamic, dynamic> value);
  String getContentLanguage();
  bool getStopPlaybackOnSwipeAway();
  int? getHomeScreenDataTime();
  Future<void> setHomeScreenDataTime(int value);
  Future<void> deleteHomeScreenDataTime();
  String? getRecentSongId();
  Future<void> setRecentSongId(String songId);
  Future<void> seedDefaults(bool updateCheckFlag);
  Map<String, dynamic> developerValues();
}
